services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_DB: readx
      POSTGRES_USER: readx
      POSTGRES_PASSWORD: readx
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
